[package]
name = "aerodymier/slidermodule"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Slider module for making sliders. Repo link: https://github.com/Aerodymier/SliderModule"

[dependencies]