[package]
name = "user/shared"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Slider module for making sliders. Repo link: https://github.com/Aerodymier/SliderModule"